dist: xenial
language: c
compiler: gcc

branches:
  only:
    - master

os:
  - linux
  - osx

addons:
  apt:
    update: true
    packages:
      - libzmq3-dev
      - python3
      - python3-pip
      - python3-setuptools
      - sbcl
  homebrew:
    packages:
      - czmq

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - METHOD=im LISP=sbcl
    - METHOD=ros LISP=ccl-bin
    - METHOD=ros LISP=ecl
    - METHOD=ros LISP=sbcl-bin
    - METHOD=sys LISP=sbcl

matrix:
  exclude:
    - os: osx
      env: METHOD=im LISP=sbcl
    - os: osx
      env: METHOD=ros LISP=ecl
    - os: osx
      env: METHOD=sys LISP=sbcl

install:
  - bash scripts/ci-install

script:
  - python3 tests/client.py --verbose
