dist: xenial
language: c
compiler: gcc

branches:
  only:
    - master

os:
  - linux
  - osx

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:darabi/lisp'
    packages:
      - g++-multilib
      - libzmq3-dev
      - libzmq3-dev:i386
      - maven
      - python3
      - python3-pip
      - python3-setuptools
      - sbcl
  homebrew:
    update: true
    packages:
      - czmq

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - METHOD=img LISP=sbcl
    - METHOD=ros LISP=abcl-bin
    - METHOD=ros LISP=ccl-bin
    - METHOD=ros LISP=cmu-bin
    - METHOD=ros LISP=ecl
    - METHOD=ros LISP=sbcl-bin
    - METHOD=loc LISP=sbcl
    - METHOD=sys LISP=sbcl
    - METHOD=usr LISP=sbcl

matrix:
  exclude:
    - os: osx
      env: METHOD=img LISP=sbcl
    - os: osx
      env: METHOD=ros LISP=abcl-bin
    - os: osx
      env: METHOD=ros LISP=cmu-bin
    - os: osx
      env: METHOD=ros LISP=ecl
    - os: osx
      env: METHOD=sys LISP=sbcl
    - os: osx
      env: METHOD=loc LISP=sbcl
    - os: osx
      env: METHOD=usr LISP=sbcl

install:
  - bash scripts/ci-install

script:
  - python3 tests/client.py --verbose
